### PR TITLE
constants: Query issue body.

### PR DESCRIPTION
**Pull request by cryptomental**
Hi, please do not review and merge yet. This is a prerequisite for MyBit-DDF.website/issues/94 to get issue description from the proxy.

### CODE REVIEW

**Comment by cryptomental** [comment]
Hi @jjperezaguinaga , @csmartinsfct  circleci deployed the PR proxy but  https://githubmybitio-ozgxzkdcoq.now.sh/api/issues returns

```
{"issues":[],"numberOfUniqueContributors":0,"totalValueOfFund":0,"totalPayoutOfFund":0}
```

I suspect that this is due to process.env.GITHUB_TOKEN missing ;) is there a way to workaround this? 
I would like to check that the query allows to fetch issue description to feed it later into DDF.

**Comment by csmartinsfct** [comment]
@cryptomental hmm it shouldn't be that. All of the required env variables are stored in now.sh, so they are used in this PR automatically. I'll have a look tomorrow morning.

**Comment by cryptomental** [comment]
> @cryptomental hmm it shouldn't be that. All of the required env variables are stored in now.sh, so they are used in this PR automatically. I'll have a look tomorrow morning.

ok, thanks a lot for looking into this!

**Comment by cryptomental** [comment]
@csmartinsfct strangely it works as expected today -) I pushed another commit and the issue body is available in the response object now. Let's leave the PR open for now, I will experiment with DDF a bit in the next days.

**Comment by cryptomental** [comment]
@csmartinsfct @mybit-bot , I changed to fetch raw body instead of bodyText as bodyText graphQL response object was swallowing markdown. Should be fine to merge now together with https://github.com/MyBitFoundation/MyBit-DDF.website/pull/176

**Comment by jjperezaguinaga** [comment]
Looking good! Tested at https://testing-issue-94-fix-ddf-mybit-io-dev.now.sh/ with https://github.com/MyBitFoundation/MyBit-DDF.website/pull/177.

**Pull request merged**
